### ISSUE TITLE
Task fails with 404 error

### ISSUE THREAD

**Issue by pavelshaforostov** [sevaa/githubactions#9]
It looks like the extension fails to reach the GitHub API endpoint.
I have several GHA called from Azure pipeline- all of them stopped  working after ~27/08/24 without any updates on my end

```
2024-09-24T10:34:38.6577313Z ##[section]Starting: API Tests
2024-09-24T10:34:38.6582435Z ==============================================================================
2024-09-24T10:34:38.6582586Z Task         : Run a GitHub Workflow
2024-09-24T10:34:38.6582683Z Description  : Starts a GitHub workflow (action), waits for completion, downloads the artifacts
2024-09-24T10:34:38.6582812Z Version      : 2.0.3
2024-09-24T10:34:38.6582877Z Author       : Seva Alekseyev
2024-09-24T10:34:38.6582968Z Help         : 
2024-09-24T10:34:38.6583026Z ==============================================================================
2024-09-24T10:34:39.0821598Z ##[error]Error: Request failed with status code 404
    at createError (C:\a\_tasks\RunWorkflow_b127b384-4d88-42ff-b32e-d8594e123878\2.0.3\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\a\_tasks\RunWorkflow_b127b384-4d88-42ff-b32e-d8594e123878\2.0.3\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\a\_tasks\RunWorkflow_b127b384-4d88-42ff-b32e-d8594e123878\2.0.3\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
2024-09-24T10:34:39.0830352Z ##[error]Not Found
2024-09-24T10:34:39.1321311Z ##[error]Exit code 1 returned from process: file name 'C:\agent\externals\node16\bin\node.exe', arguments '"C:\a\_tasks\RunWorkflow_b127b384-4d88-42ff-b32e-d8594e123878\2.0.3/RunWorkflow.js"'.
2024-09-24T10:34:39.1326259Z ##[section]Finishing: API Tests
```

**Comment by sevaa** [comment]
A test run against my repo and my action just worked, so it's not across the board. Could it be that your PAT has expired? Can you try GitHub REST API from an interactive REST client of your choice? "[List workflows](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#list-repository-workflows)" is a safe one.

**Comment by pavelshaforostov** [comment]
Looks like that's it, I've used another user PAT and it works now. Service connection is still used in multiple places but broken for GH actions. GitHub should return 401 instead of 404, but nothing to do with that.
Thanks for your quick reply and assistance

**Comment by sevaa** [comment]
Good to know. Close the issue then.
